version: 2

sources:
  - name: raw
    schema: products_dataset
    tables:
      - name: products_2
        columns:
          - name: product_id
            tests:
              - not_null
              - unique
          - name: product_name
            tests:
              - not_null
          - name: search_term
            tests:
              - not_null
          - name: price
            tests:
              - not_null